export const FETCH_ALL_CATEGORIES="FETCH_ALL_CATEGORIES";
export const FETCH_CATEGORY_BYID = "FETCH_CATEGORY_BYID";
export const DELETE_CATEGORY ="DELETE_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

//for products 
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_PRODUCT_BYID = "FETCH_PRODUCT_BYID";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
